#!/usr/bin/env node

const yargs = require("yargs");

yargs
  .usage("Usage: $0 <command> [options]")
  .commandDir("cmds")
  .showHelpOnFail(true)
  .help(
    'help',
    'Show usage instructions.'
  )
  .command({
    command: '*',
    handler() { yargs.showHelp(); console.log('\n'); }
  })
  .demandCommand()
  .help().argv;
