;; -*- mode: eask; lexical-binding: t -*-

(package "mini.pkg.1"
         "0.0.1"
         "Minimal test package")

(website-url "https://github.com/emacs-eask/cli/tree/master/test/fixtures/mini.pkg.1")
(keywords "test" "local")

(package-file "mini.pkg.1.el")

(files "files/*.el")

(script "test" "echo \"Have a nice day!~ ;)\"")
(script "extra" "echo :")
(script "info" "eask info")

(eask-defcommand mini-test-1 "Test command 1." (message "Test 1"))
(eask-defcommand mini-test-2 "Test command 2." (message "Test 2"))
(eask-defcommand mini-test-3
  "Test command 3."
  (message "Test 3: %s" eask-rest))

(source 'gnu)
(source 'melpa)
;; (source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "f")
(depends-on "s")
(depends-on "fringe-helper")

;; File install
(depends-on "mini.pkg.2" :file "./mini.pkg.2")

;; VC install
(when (version<= "29.1" emacs-version)
  ;; XXX: This takes too long to test, disable for now.
  ;;(depends-on "msgu" :vc "https://github.com/jcs-elpa/msgu")
  )

;; Try out
(depends-on "indent-control" :try)
(depends-on "auto-rename-tag" :try "https://raw.githubusercontent.com/emacs-vs/auto-rename-tag/refs/heads/master/auto-rename-tag.el")

;; Recipe install
(depends-on "watch-cursor"
            :repo "jcs-elpa/watch-cursor" :fetcher 'github)
;; (depends-on "organize-imports-java"
;;             :repo "jcs-elpa/organize-imports-java"
;;             :fetcher 'github
;;             :files '(:defaults "sdk" "default"))

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
