(package "check-eask"
         "0.0.1"
         "Test the command `check-eask'")

(package-file "check-eask.el")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432

;;
;;; Below are error to lint

(package "" "" "")              ; duplicate `package` directive

(package-file "check-eask.el")  ; duplicate `package-file` directive

(source "gnu")                  ; duplicate archives
(source "gnu")

(source "magic-archive")        ; Unkown archive

(depends-on "emacs" "26.1")     ; duplicate `emacs` dependency
(depends-on "emacs")

(depends-on "s")                ; duplicate dependency
(depends-on "s")
