(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432

;;
;;; Below are errors/warnings to lint

(package "check-metadata?"             ; unmatched
         "0.0.1?"                      ; unmatched and invalid version syntax
         "Test for unmatch metadata?"  ; unmatched
         )

(website-url "https://github.com/emacs-eask/check-metadata?")  ; unmatched
(keywords "metadata?")  ; missing

(package-file "check-metadata.el")

(depends-on "s")   ; unmatch dependency
