;; -*- mode: eask; lexical-binding: t -*-

(package "keywords-ok"
         "1.0.0"
         "")

(keywords "tools")

(package-file "keywords-ok.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")
