;;; clean-elc.el --- Remove byte compiled files generated by cask build  -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; Remove byte compiled files generated by cask build
;;
;;   $ eask clean-elc
;;

;;; Code:

(load-file (expand-file-name
            "_prepare.el"
            (file-name-directory (nth 1 (member "-scriptload" command-line-args)))))

(eask-start
  (if-let ((elcs (eask-package-elc-files)))
      (progn
        (dolist (elc elcs)
          (ignore-errors (delete-file elc))
          (eask-log "Deleting %s..." elc))
        (eask-info "(Total of %s .elc files deleted)" (length elcs)))
    (eask-info "(No .elc file found in workspace)")))

;;; clean-elc.el ends here
