;;; clean-elc.el --- Remove byte compiled files generated by cask build  -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; Remove byte compiled files generated by cask build
;;
;;   $ eask clean-elc
;;

;;; Code:

(load-file (expand-file-name
            "_prepare.el"
            (file-name-directory (nth 1 (member "-scriptload" command-line-args)))))

(eask-start
  (let ((elcs (eask--f-entries default-directory "\\.elc$")))
    (when (zerop (length elcs))
      (message "Workspace is already cleaned"))
    (dolist (elc elcs)
      (ignore-errors (delete-file elc))
      (message "Deleting %s..." elc))))

;;; clean-elc.el ends here
