(package "mini.emacs.d"
         "0.0.1"
         "Minimal Emacs configuration to run `eask`; only for testing purposes!")

(depends-on "emacs" "26.1")

(depends-on "company-fuzzy")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
