(elsa-in-file "d:/_lang/elisp/_emacs/emacs-28.2/share/emacs/28.2/lisp/subr.el")
(elsa-declare-defvar gensym-counter (const 0))
(elsa-declare-defvar key-substitution-in-progress nil)
(elsa-declare-defvar esc-map mixed)
(elsa-declare-defvar ctl-x-4-map mixed)
(elsa-declare-defvar ctl-x-5-map mixed)
(elsa-declare-defvar tab-prefix-map mixed)
(elsa-declare-defvar ctl-x-map mixed)
(elsa-declare-defvar global-map mixed)
(elsa-declare-defvar listify-key-sequence-1 (readonly int))
(elsa-declare-defvar inhibit--record-char nil)
(elsa-declare-defvar delay-mode-hooks nil)
(elsa-declare-defvar delayed-mode-hooks nil)
(elsa-declare-defvar delayed-after-hook-functions nil)
(elsa-declare-defvar change-major-mode-after-body-hook nil)
(elsa-declare-defvar after-change-major-mode-hook nil)
(elsa-declare-defvar major-mode--suspended nil)
(elsa-declare-defvar minor-mode-list (list mixed))
(elsa-declare-defvar read-key-empty-map (readonly mixed))
(elsa-declare-defvar read-key-full-map (readonly mixed))
(elsa-declare-defvar read-key-delay (const 0.01))
(elsa-declare-defvar read-passwd-map mixed)
(elsa-declare-defvar read-number-history nil)
(elsa-declare-defvar read-char-choice-use-read-key nil)
(elsa-declare-defvar read-char-history nil)
(elsa-declare-defvar read-char-from-minibuffer-map mixed)
(elsa-declare-defvar read-char-from-minibuffer-map-hash (readonly mixed))
(elsa-declare-defvar empty-history unbound)
(elsa-declare-defvar y-or-n-p-history-variable nil)
(elsa-declare-defvar y-or-n-p-map mixed)
(elsa-declare-defvar y-or-n-p-use-read-key nil)
(elsa-declare-defvar suspend-hook nil)
(elsa-declare-defvar suspend-resume-hook nil)
(elsa-declare-defvar temp-buffer-show-hook nil)
(elsa-declare-defvar temp-buffer-setup-hook nil)
(elsa-declare-defvar user-emacs-directory nil)
(elsa-declare-defvar yank-handled-properties unbound)
(elsa-declare-defvar yank-excluded-properties unbound)
(elsa-declare-defvar yank-undo-function unbound)
(elsa-declare-defvar undo--combining-change-calls nil)
(elsa-declare-defvar split-string-default-separators (readonly (const "[ 	
]+")))
(elsa-declare-defvar after-load-functions nil)
(elsa-declare-defvar delayed-warnings-hook (list mixed))
(elsa-declare-defvar word-move-empty-char-table nil)
(elsa-declare-defvar text-clone--maintaining nil)
(elsa-declare-defvar called-interactively-p-functions nil)
(elsa-declare-defvar internal--funcall-interactively (readonly mixed))
(elsa-declare-defvar progress-reporter--pulse-characters (vector mixed))
(elsa-declare-defvar version-separator (readonly (const ".")))
(elsa-declare-defvar version-regexp-alist (readonly (list (list mixed))))
(elsa-declare-defvar package--builtin-versions mixed)
(elsa-declare-defvar definition-prefixes mixed)
(elsa-declare-defvar menu-bar-separator (readonly (list (const "--"))))
(elsa-declare-defvar regexp-unmatchable (readonly (const "\\`a\\`")))
(elsa-declare-defun declare-function (_fn _file &rest _args) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun noreturn (form) (function (mixed) mixed))
(elsa-declare-defun 1value (form) (function (mixed) mixed))
(elsa-declare-defun def-edebug-spec (symbol spec) (function (mixed mixed) mixed))
(elsa-declare-defun def-edebug-elem-spec (name spec) (function (mixed mixed) mixed))
(elsa-declare-defun lambda (&rest cdr) (function (&rest mixed) mixed))
(elsa-declare-defun prog2 (form1 form2 &rest body) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun setq-default (&rest args) (function (&rest mixed) mixed))
(elsa-declare-defun setq-local (&rest pairs) (function (&rest mixed) mixed))
(elsa-declare-defun defvar-local (var val &optional docstring) (function (mixed mixed mixed) mixed))
(elsa-declare-defun buffer-local-boundp (symbol buffer) (function (mixed mixed) mixed))
(elsa-declare-defun push (newelt place) (function (mixed mixed) mixed))
(elsa-declare-defun pop (place) (function (mixed) mixed))
(elsa-declare-defun when (cond &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun unless (cond &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun subr-primitive-p (object) (function (mixed) bool))
(elsa-declare-defun xor (cond1 cond2) (function (mixed mixed) mixed))
(elsa-declare-defun dolist (spec &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun dotimes (spec &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun declare (&rest _specs) (function (&rest mixed) mixed))
(elsa-declare-defun ignore-errors (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun ignore-error (condition &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun gensym (&optional prefix) (function (mixed) symbol))
(elsa-declare-defun ignore (&rest _arguments) (function (&rest mixed) nil))
(elsa-declare-defun always (&rest _arguments) (function (&rest mixed) t))
(elsa-declare-defun error (&rest args) (function (&rest mixed) mixed))
(elsa-declare-defun user-error (format &rest args) (function (mixed &rest mixed) mixed))
(elsa-declare-defun define-error (name message &optional parent) (function (mixed mixed mixed) mixed))
(elsa-declare-defun frame-configuration-p (object) (function (mixed) bool))
(elsa-declare-defun apply-partially (fun &rest args) (function (mixed &rest mixed) (function (mixed mixed) mixed)))
(elsa-declare-defun zerop (number) (function (mixed) bool))
(elsa-declare-defun fixnump (object) (function (mixed) bool))
(elsa-declare-defun bignump (object) (function (mixed) bool))
(elsa-declare-defun lsh (value count) (function (mixed mixed) int))
(elsa-declare-defun internal--compiler-macro-cXXr (form x) (function (mixed mixed) mixed))
(elsa-declare-defun caar (x) (function (mixed) mixed))
(elsa-declare-defun cadr (x) (function (mixed) mixed))
(elsa-declare-defun cdar (x) (function (mixed) mixed))
(elsa-declare-defun cddr (x) (function (mixed) mixed))
(elsa-declare-defun caaar (x) (function (mixed) mixed))
(elsa-declare-defun caadr (x) (function (mixed) mixed))
(elsa-declare-defun cadar (x) (function (mixed) mixed))
(elsa-declare-defun caddr (x) (function (mixed) mixed))
(elsa-declare-defun cdaar (x) (function (mixed) mixed))
(elsa-declare-defun cdadr (x) (function (mixed) mixed))
(elsa-declare-defun cddar (x) (function (mixed) mixed))
(elsa-declare-defun cdddr (x) (function (mixed) mixed))
(elsa-declare-defun caaaar (x) (function (mixed) mixed))
(elsa-declare-defun caaadr (x) (function (mixed) mixed))
(elsa-declare-defun caadar (x) (function (mixed) mixed))
(elsa-declare-defun caaddr (x) (function (mixed) mixed))
(elsa-declare-defun cadaar (x) (function (mixed) mixed))
(elsa-declare-defun cadadr (x) (function (mixed) mixed))
(elsa-declare-defun caddar (x) (function (mixed) mixed))
(elsa-declare-defun cadddr (x) (function (mixed) mixed))
(elsa-declare-defun cdaaar (x) (function (mixed) mixed))
(elsa-declare-defun cdaadr (x) (function (mixed) mixed))
(elsa-declare-defun cdadar (x) (function (mixed) mixed))
(elsa-declare-defun cdaddr (x) (function (mixed) mixed))
(elsa-declare-defun cddaar (x) (function (mixed) mixed))
(elsa-declare-defun cddadr (x) (function (mixed) mixed))
(elsa-declare-defun cdddar (x) (function (mixed) mixed))
(elsa-declare-defun cddddr (x) (function (mixed) mixed))
(elsa-declare-defun last (list &optional n) (function (mixed mixed) mixed))
(elsa-declare-defun butlast (list &optional n) (function (mixed mixed) mixed))
(elsa-declare-defun nbutlast (list &optional n) (function (mixed mixed) mixed))
(elsa-declare-defun delete-dups (list) (function (mixed) mixed))
(elsa-declare-defun delete-consecutive-dups (list &optional circular) (function (mixed mixed) mixed))
(elsa-declare-defun number-sequence (from &optional to inc) (function (mixed mixed mixed) mixed))
(elsa-declare-defun copy-tree (tree &optional vecp) (function (mixed mixed) mixed))
(elsa-declare-defun assoc-default (key alist &optional test default) (function (mixed mixed mixed mixed) nil))
(elsa-declare-defun member-ignore-case (elt list) (function (mixed mixed) mixed))
(elsa-declare-defun assoc-delete-all (key alist &optional test) (function (mixed mixed mixed) mixed))
(elsa-declare-defun assq-delete-all (key alist) (function (mixed mixed) mixed))
(elsa-declare-defun rassq-delete-all (value alist) (function (mixed mixed) mixed))
(elsa-declare-defun alist-get (key alist &optional default remove testfn) (function (mixed mixed mixed mixed mixed) mixed))
(elsa-declare-defun remove (elt seq) (function (mixed mixed) mixed))
(elsa-declare-defun remq (elt list) (function (mixed mixed) mixed))
(elsa-declare-defun kbd (keys) (function (mixed) mixed))
(elsa-declare-defun undefined nil (function nil unbound))
(elsa-declare-defun suppress-keymap (map &optional nodigits) (function (mixed mixed) mixed))
(elsa-declare-defun make-composed-keymap (maps &optional parent) (function (mixed mixed) (cons (const keymap) (list mixed))))
(elsa-declare-defun define-key-after (keymap key definition &optional after) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun define-prefix-command (command &optional mapvar name) (function (mixed mixed mixed) mixed))
(elsa-declare-defun map-keymap-sorted #'keymap (function (mixed mixed) mixed))
(elsa-declare-defun keymap--menu-item-binding (val) (function (mixed) mixed))
(elsa-declare-defun keymap--menu-item-with-binding (item binding) (function (mixed mixed) mixed))
(elsa-declare-defun keymap--merge-bindings (val1 val2) (function (mixed mixed) mixed))
(elsa-declare-defun keymap-canonicalize (map) (function (mixed) mixed))
(elsa-declare-defun keyboard-translate (from to) (function (mixed mixed) mixed))
(elsa-declare-defun global-set-key (key command) (function (mixed mixed) mixed))
(elsa-declare-defun local-set-key (key command) (function (mixed mixed) mixed))
(elsa-declare-defun global-unset-key (key) (function (mixed) mixed))
(elsa-declare-defun local-unset-key (key) (function (mixed) nil))
(elsa-declare-defun local-key-binding (keys &optional accept-default) (function (mixed mixed) mixed))
(elsa-declare-defun global-key-binding (keys &optional accept-default) (function (mixed mixed) mixed))
(elsa-declare-defun substitute-key-definition (olddef newdef keymap &optional oldmap prefix) (function (mixed mixed mixed mixed mixed) mixed))
(elsa-declare-defun substitute-key-definition-key (defn olddef newdef prefix keymap) (function (mixed mixed mixed mixed mixed) mixed))
(elsa-declare-defun listify-key-sequence (key) (function (mixed) mixed))
(elsa-declare-defun eventp (object) (function (mixed) (is int)))
(elsa-declare-defun event-modifiers (event) (function (mixed) mixed))
(elsa-declare-defun event-basic-type (event) (function (mixed) mixed))
(elsa-declare-defun mouse-movement-p (object) (function (mixed) bool))
(elsa-declare-defun mouse-event-p (object) (function (mixed) (list mixed)))
(elsa-declare-defun event-start (event) (function (mixed) (diff mixed nil)))
(elsa-declare-defun event-end (event) (function (mixed) (diff mixed nil)))
(elsa-declare-defun event-click-count (event) (function (mixed) mixed))
(elsa-declare-defun event-line-count (event) (function (mixed) mixed))
(elsa-declare-defun posnp (obj) (function (mixed) (is int)))
(elsa-declare-defun posn-window (position) (function (mixed) mixed))
(elsa-declare-defun posn-area (position) (function (mixed) symbol))
(elsa-declare-defun posn-point (position) (function (mixed) mixed))
(elsa-declare-defun posn-set-point (position) (function (mixed) (or int nil)))
(elsa-declare-defun posn-x-y (position) (function (mixed) mixed))
(elsa-declare-defun posn-col-row (position) (function (mixed) mixed))
(elsa-declare-defun posn-actual-col-row (position) (function (mixed) mixed))
(elsa-declare-defun posn-timestamp (position) (function (mixed) mixed))
(elsa-declare-defun posn-string (position) (function (mixed) (or (cons mixed mixed) nil)))
(elsa-declare-defun posn-image (position) (function (mixed) mixed))
(elsa-declare-defun posn-object (position) (function (mixed) mixed))
(elsa-declare-defun posn-object-x-y (position) (function (mixed) mixed))
(elsa-declare-defun posn-object-width-height (position) (function (mixed) mixed))
(elsa-declare-defun values--store-value (value) (function (mixed) mixed))
(elsa-declare-defun log10 (x) (function (mixed) mixed))
(elsa-declare-defun add-hook (hook function &optional depth local) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun remove-hook (hook function &optional local) (function (mixed mixed mixed) mixed))
(elsa-declare-defun letrec (binders &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun dlet (binders &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun with-wrapper-hook (hook args &rest body) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun subr--with-wrapper-hook-no-warnings (hook args &rest body) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun add-to-list (list-var element &optional append compare-fn) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun add-to-ordered-list (list-var element &optional order) (function (mixed mixed mixed) mixed))
(elsa-declare-defun add-to-history (history-var newelt &optional maxelt keep-all) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun run-mode-hooks (&rest hooks) (function (&rest mixed) mixed))
(elsa-declare-defun delay-mode-hooks (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun provided-mode-derived-p (mode &rest modes) (function (mixed &rest mixed) mixed))
(elsa-declare-defun derived-mode-p (&rest modes) (function (&rest mixed) mixed))
(elsa-declare-defun major-mode-suspend nil (function nil mixed))
(elsa-declare-defun major-mode-restore (&optional avoided-modes) (function (mixed) mixed))
(elsa-declare-defun add-minor-mode (toggle name &optional keymap after toggle-fun) (function (mixed mixed mixed mixed mixed) mixed))
(elsa-declare-defun autoloadp (object) (function (mixed) bool))
(elsa-declare-defun define-symbol-prop (symbol prop val) (function (mixed mixed mixed) mixed))
(elsa-declare-defun symbol-file (symbol &optional type) (function (mixed mixed) mixed))
(elsa-declare-defun locate-library (library &optional nosuffix path interactive-call) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun start-process (name buffer program &rest program-args) (function (mixed mixed mixed &rest mixed) mixed))
(elsa-declare-defun process-lines-handling-status (program status-handler &rest args) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun process-lines (program &rest args) (function (mixed &rest mixed) mixed))
(elsa-declare-defun process-lines-ignore-status (program &rest args) (function (mixed &rest mixed) mixed))
(elsa-declare-defun process-live-p (process) (function (mixed) (list mixed)))
(elsa-declare-defun process-kill-buffer-query-function nil (function nil bool))
(elsa-declare-defun process-get (process propname) (function (mixed mixed) mixed))
(elsa-declare-defun process-put (process propname value) (function (mixed mixed mixed) (list mixed)))
(elsa-declare-defun memory-limit nil (function nil (diff mixed nil)))
(elsa-declare-defun read-key (&optional prompt disable-fallbacks) (function (mixed mixed) mixed))
(elsa-declare-defun read--potential-mouse-event nil (function nil mixed))
(elsa-declare-defun read-password--hide-password nil (function nil mixed))
(elsa-declare-defun read-passwd (prompt &optional confirm default) (function (mixed mixed mixed) mixed))
(elsa-declare-defun read-number (prompt &optional default hist) (function (mixed mixed mixed) mixed))
(elsa-declare-defun read-char-choice (prompt chars &optional inhibit-keyboard-quit) (function (mixed mixed mixed) mixed))
(elsa-declare-defun read-char-choice-with-read-key (prompt chars &optional inhibit-keyboard-quit) (function (mixed mixed mixed) mixed))
(elsa-declare-defun sit-for (seconds &optional nodisp obsolete) (function (mixed mixed mixed) mixed))
(elsa-declare-defun goto-char--read-natnum-interactive (prompt) (function (mixed) (mixed)))
(elsa-declare-defun read-char-from-minibuffer-insert-char nil (function nil mixed))
(elsa-declare-defun read-char-from-minibuffer-insert-other nil (function nil mixed))
(elsa-declare-defun read-char-from-minibuffer (prompt &optional chars history) (function (mixed mixed mixed) mixed))
(elsa-declare-defun y-or-n-p-insert-y nil (function nil mixed))
(elsa-declare-defun y-or-n-p-insert-n nil (function nil mixed))
(elsa-declare-defun y-or-n-p-insert-other nil (function nil mixed))
(elsa-declare-defun y-or-n-p (prompt) (function (mixed) nil))
(elsa-declare-defun atomic-change-group (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun prepare-change-group (&optional buffer) (function (mixed) ((cons (diff mixed nil) unbound))))
(elsa-declare-defun activate-change-group (handle) (function (mixed) (or (cons (cons mixed mixed) unbound) nil)))
(elsa-declare-defun accept-change-group (handle) (function (mixed) bool))
(elsa-declare-defun cancel-change-group (handle) (function (mixed) mixed))
(elsa-declare-defun momentary-string-display (string pos &optional exit-char message) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun copy-overlay (o) (function (mixed) mixed))
(elsa-declare-defun remove-overlays (&optional beg end name val) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun buffer-narrowed-p nil (function nil bool))
(elsa-declare-defun find-tag-default-bounds nil (function nil (or nil (cons int int))))
(elsa-declare-defun find-tag-default nil (function nil (or string nil)))
(elsa-declare-defun find-tag-default-as-regexp nil (function nil string))
(elsa-declare-defun find-tag-default-as-symbol-regexp nil (function nil string))
(elsa-declare-defun play-sound (sound) (function (mixed) mixed))
(elsa-declare-defun shell-quote-argument (argument) (function (mixed) mixed))
(elsa-declare-defun string-to-list (string) (function (mixed) (list mixed)))
(elsa-declare-defun string-to-vector (string) (function (mixed) (vector mixed)))
(elsa-declare-defun string-or-null-p (object) (function (mixed) (is string)))
(elsa-declare-defun booleanp (object) (function (mixed) bool))
(elsa-declare-defun special-form-p (object) (function (mixed) bool))
(elsa-declare-defun macrop (object) (function (mixed) (or bool (list mixed))))
(elsa-declare-defun field-at-pos (pos) (function (mixed) mixed))
(elsa-declare-defun sha1 (object &optional start end binary) (function (mixed mixed mixed mixed) string))
(elsa-declare-defun function-get (f prop &optional autoload) (function (mixed mixed mixed) nil))
(elsa-declare-defun remove-yank-excluded-properties (start end) (function (mixed mixed) mixed))
(elsa-declare-defun insert-for-yank (string) (function (mixed) mixed))
(elsa-declare-defun insert-for-yank-1 (string) (function (mixed) mixed))
(elsa-declare-defun insert-buffer-substring-no-properties (buffer &optional start end) (function (mixed mixed mixed) mixed))
(elsa-declare-defun insert-buffer-substring-as-yank (buffer &optional start end) (function (mixed mixed mixed) mixed))
(elsa-declare-defun insert-into-buffer (buffer &optional start end) (function (mixed mixed mixed) nil))
(elsa-declare-defun replace-string-in-region (string replacement &optional start end) (function (mixed mixed mixed mixed) (or number nil)))
(elsa-declare-defun replace-regexp-in-region (regexp replacement &optional start end) (function (mixed mixed mixed mixed) (or number nil)))
(elsa-declare-defun yank-handle-font-lock-face-property (face start end) (function (mixed mixed mixed) mixed))
(elsa-declare-defun yank-handle-category-property (category start end) (function (mixed mixed mixed) mixed))
(elsa-declare-defun start-process-shell-command (name buffer command) (function (mixed mixed mixed) mixed))
(elsa-declare-defun start-file-process-shell-command (name buffer command) (function (mixed mixed mixed) mixed))
(elsa-declare-defun call-process-shell-command (command &optional infile buffer display &rest args) (function (mixed mixed mixed mixed &rest mixed) (or nil int string)))
(elsa-declare-defun process-file-shell-command (command &optional infile buffer display &rest args) (function (mixed mixed mixed mixed &rest mixed) mixed))
(elsa-declare-defun call-shell-region (start end command &optional delete buffer) (function (mixed mixed mixed mixed mixed) (or nil int string)))
(elsa-declare-defun track-mouse (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun with-current-buffer (buffer-or-name &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun internal--before-with-selected-window (window) (function (mixed) (mixed mixed mixed mixed)))
(elsa-declare-defun internal--after-with-selected-window (state) (function (mixed) mixed))
(elsa-declare-defun generate-new-buffer (name &optional inhibit-buffer-hooks) (function (mixed mixed) buffer))
(elsa-declare-defun with-selected-window (window &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun with-selected-frame (frame &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun save-window-excursion (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun internal-temp-output-buffer-show (buffer) (function (mixed) nil))
(elsa-declare-defun with-output-to-temp-buffer (bufname &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun with-temp-file (file &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun with-temp-message (message &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun with-temp-buffer (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun with-silent-modifications (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun with-output-to-string (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun with-local-quit (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun while-no-input (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun condition-case-unless-debug (var bodyform &rest handlers) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun with-demoted-errors (format &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun combine-after-change-calls (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun combine-change-calls-1 (beg end body) (function (mixed mixed mixed) nil))
(elsa-declare-defun combine-change-calls (beg end &rest body) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun undo--wrap-and-run-primitive-undo (beg end list) (function (mixed mixed mixed) nil))
(elsa-declare-defun with-case-table (table &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun with-file-modes (modes &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun with-existing-directory (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun save-match-data (&rest body) (function (&rest mixed) mixed))
(elsa-declare-defun match-string (num &optional string) (function (mixed mixed) (or string nil)))
(elsa-declare-defun match-string-no-properties (num &optional string) (function (mixed mixed) (or string nil)))
(elsa-declare-defun match-substitute-replacement (replacement &optional fixedcase literal string subexp) (function (mixed mixed mixed mixed mixed) nil))
(elsa-declare-defun looking-back (regexp &optional limit greedy) (function (mixed mixed mixed) bool))
(elsa-declare-defun looking-at-p (regexp) (function (mixed) bool))
(elsa-declare-defun string-match-p (regexp string &optional start) (function (mixed mixed mixed) (or int nil)))
(elsa-declare-defun subregexp-context-p (regexp pos &optional start) (function (mixed mixed mixed) bool))
(elsa-declare-defun split-string (string &optional separators omit-nulls trim) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun combine-and-quote-strings (strings &optional separator) (function (mixed mixed) string))
(elsa-declare-defun split-string-and-unquote (string &optional separator) (function (mixed mixed) mixed))
(elsa-declare-defun subst-char-in-string (fromchar tochar string &optional inplace) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun string-replace (from-string to-string in-string) (function (mixed mixed mixed) mixed))
(elsa-declare-defun replace-regexp-in-string (regexp rep string &optional fixedcase literal subexp start) (function (mixed mixed mixed mixed mixed mixed mixed) mixed))
(elsa-declare-defun string-prefix-p (prefix string &optional ignore-case) (function (mixed mixed mixed) bool))
(elsa-declare-defun string-suffix-p (suffix string &optional ignore-case) (function (mixed mixed mixed) bool))
(elsa-declare-defun bidi-string-mark-left-to-right (str) (function (mixed) mixed))
(elsa-declare-defun string-greaterp (string1 string2) (function (mixed mixed) bool))
(elsa-declare-defun load-history-regexp (file) (function (mixed) string))
(elsa-declare-defun load-history-filename-element (file-regexp) (function (mixed) mixed))
(elsa-declare-defun eval-after-load (file form) (function (mixed mixed) mixed))
(elsa-declare-defun with-eval-after-load (file &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun do-after-load-evaluation (abs-file) (function (mixed) mixed))
(elsa-declare-defun display-delayed-warnings nil (function nil nil))
(elsa-declare-defun collapse-delayed-warnings nil (function nil mixed))
(elsa-declare-defun delay-warning (type message &optional level buffer-name) (function (mixed mixed mixed mixed) (cons (mixed mixed mixed mixed) mixed)))
(elsa-declare-defun add-to-invisibility-spec (element) (function (mixed) (cons mixed (t))))
(elsa-declare-defun remove-from-invisibility-spec (element) (function (mixed) mixed))
(elsa-declare-defun with-syntax-table (table &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun make-syntax-table (&optional oldtable) (function (mixed) mixed))
(elsa-declare-defun syntax-after (pos) (function (mixed) mixed))
(elsa-declare-defun syntax-class (syntax) (function (mixed) (or int nil)))
(elsa-declare-defun forward-word-strictly (&optional arg) (function (mixed) bool))
(elsa-declare-defun backward-word-strictly (&optional arg) (function (mixed) bool))
(elsa-declare-defun forward-whitespace (arg) (function (mixed) mixed))
(elsa-declare-defun forward-symbol (arg) (function (mixed) mixed))
(elsa-declare-defun forward-same-syntax (&optional arg) (function (mixed) mixed))
(elsa-declare-defun text-clone--maintain (ol1 after beg end &optional _len) (function (mixed mixed mixed mixed mixed) mixed))
(elsa-declare-defun text-clone-create (start end &optional spreadp syntax) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun define-mail-user-agent (symbol composefunc sendfunc &optional abortfunc hookvar) (function (mixed mixed mixed mixed mixed) mixed))
(elsa-declare-defun backtrace-frames (&optional base) (function (mixed) mixed))
(elsa-declare-defun backtrace-frame (nframes &optional base) (function (mixed mixed) mixed))
(elsa-declare-defun called-interactively-p (&optional kind) (function (mixed) bool))
(elsa-declare-defun interactive-p nil (function nil bool))
(elsa-declare-defun internal-push-keymap (keymap symbol) (function (mixed mixed) mixed))
(elsa-declare-defun internal-pop-keymap (keymap symbol) (function (mixed mixed) mixed))
(elsa-declare-defun set-transient-map (map &optional keep-pred on-exit) (function (mixed mixed mixed) (function nil mixed)))
(elsa-declare-defun progress-reporter-update (reporter &optional value suffix) (function (mixed mixed mixed) mixed))
(elsa-declare-defun make-progress-reporter (message &optional min-value max-value current-value min-change min-time) (function (mixed mixed mixed mixed mixed mixed) (cons (diff mixed nil) (vector mixed))))
(elsa-declare-defun progress-reporter-force-update (reporter &optional value new-message suffix) (function (mixed mixed mixed mixed) mixed))
(elsa-declare-defun progress-reporter-do-update (reporter value &optional suffix) (function (mixed mixed mixed) (or string nil)))
(elsa-declare-defun progress-reporter-done (reporter) (function (mixed) string))
(elsa-declare-defun dotimes-with-progress-reporter (spec reporter-or-message &rest body) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun dolist-with-progress-reporter (spec reporter-or-message &rest body) (function (mixed mixed &rest mixed) mixed))
(elsa-declare-defun version-to-list (ver) (function (mixed) mixed))
(elsa-declare-defun version-list-< (l1 l2) (function (mixed mixed) bool))
(elsa-declare-defun version-list-= (l1 l2) (function (mixed mixed) bool))
(elsa-declare-defun version-list-<= (l1 l2) (function (mixed mixed) bool))
(elsa-declare-defun version-list-not-zero (lst) (function (mixed) mixed))
(elsa-declare-defun version< (v1 v2) (function (mixed mixed) bool))
(elsa-declare-defun version<= (v1 v2) (function (mixed mixed) bool))
(elsa-declare-defun version= (v1 v2) (function (mixed mixed) bool))
(elsa-declare-defun package--description-file (dir) (function (mixed) string))
(elsa-declare-defun with-mutex (mutex &rest body) (function (mixed &rest mixed) mixed))
(elsa-declare-defun apropos-internal (regexp &optional predicate) (function (mixed mixed) mixed))
(elsa-declare-defun register-definition-prefixes (file prefixes) (function (mixed mixed) mixed))
(elsa-declare-defun unmsys--file-name (file) (function (mixed) mixed))
(elsa-declare-defun flatten-tree (tree) (function (mixed) mixed))
(elsa-declare-defun string-trim-left (string &optional regexp) (function (mixed mixed) mixed))
(elsa-declare-defun string-trim-right (string &optional regexp) (function (mixed mixed) mixed))
(elsa-declare-defun string-trim (string &optional trim-left trim-right) (function (mixed mixed mixed) mixed))
(elsa-declare-defun run-hook-query-error-with-timeout (hook) (function (mixed) mixed))
(elsa-declare-defun internal--fill-string-single-line (str) (function (mixed) mixed))
(elsa-declare-defun internal--format-docstring-line (string &rest objects) (function (mixed &rest mixed) mixed))
(elsa-declare-defun json-available-p nil (function nil mixed))
(elsa-declare-defun ensure-list (object) (function (mixed) (list mixed)))
