(package ".emacs.d"
         "0.0.1"
         "Minimal test configuration")

(website-url "https://github.com/emacs-eask/cli/tree/master/test/fixtures/home/.emacs.d")
(keywords "test")

(depends-on "emacs" "26.1")
(depends-on "csharp-mode")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
