(package "mini.emacs.pkg"
         "0.0.1"
         "Minimal Emacs package to simulate development environment; only for testing purposes!")

(website-url "https://github.com/emacs-eask/mini.emacs.pkg")
(keywords "test")

(package-file "mini.emacs.pkg.el")

(files "*.el" "files/*.el")

(scripts "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "26.1")
(depends-on "f")
(depends-on "s")
(depends-on "fringe-helper")
(depends-on "watch-cursor"
            :repo "jcs-elpa/watch-cursor" :fetcher 'github)
(depends-on "organize-imports-java"
            :repo "jcs-elpa/organize-imports-java"
            :fetcher 'github
            :files '(:defaults "sdk" "default"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
