;; -*- mode: eask; lexical-binding: t -*-

(package "outdated-upgrade"
         "0.0.1"
         "Test project for command outdated and upgrade")

(package-file "outdated-upgrade.el")

(source 'gnu)
(source 'melpa)

(depends-on "f")
(depends-on "s")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
