;;; lint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.
;; This is about the only thing that causes melpazoid to error
;; Package-Version: (("foo", 12345

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from checkdoc-fail.el

(register-definition-prefixes "checkdoc-fail" '("my-foo"))


;;; Generated autoloads from elisp-lint-ok.el

(register-definition-prefixes "elisp-lint-ok" '("elisp-lint-ok-foo"))


;;; End of scraped data

(provide 'lint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lint-autoloads.el ends here
