(package "ert"
         "0.0.1"
         "Test project for command `ert'")

(package-file "ert.el")

(source 'gnu)
(source 'melpa)

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
