(package "ecukes"
         "0.0.1"
         "Test project for command `ecukes'")

(package-file "ecukes.el")

(source 'gnu)
(source 'melpa)

(development
 (depends-on "ecukes"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
