;; -*- mode: eask; lexical-binding: t -*-

(package "foo-no"
         "0.0.1"
         "")

(website-url "")
(keywords )

(package-file "foo-no.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")
