(package "link"
         "1.0.0"
         "")

(website-url "")
(keywords )

(package-file "link.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")
