(package "check-eask"
         "0.0.1"
         "Test the command `check-eask'")

(package-file "check-eask.el")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432

;;
;;; Below are error to lint

(package-file "check-eask.el")  ; duplicate `package-file`

(source "gnu")                  ; duplicate archives
(source "gnu")

(source "magic-archive")        ; Unkown archive

(depends-on "s")                ; duplicate dependencies
(depends-on "s")
