;; -*- mode: eask; lexical-binding: t -*-

(package "home"
         "0.0.1"
         "Minimal test for global config")

(website-url "https://github.com/emacs-eask/mini.eask")
(keywords "test")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "yaml-mode")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
