;; -*- mode: eask; lexical-binding: t -*-

(package "mini.pkg.2"
         "0.0.1"
         "Minimal test package")

(website-url "https://github.com/emacs-eask/cli/tree/master/test/fixtures/mini.pkg.2")
(keywords "test")

(package-file "mini.pkg.2.el")

(files "files/*.el")

(script "test" "echo \"Have a nice day!~ ;)\"")
(script "info" "eask info")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "f")
(depends-on "s")
(depends-on "fringe-helper")
(depends-on "watch-cursor"
            :repo "jcs-elpa/watch-cursor" :fetcher 'github)
(depends-on "organize-imports-java"
            :repo "jcs-elpa/organize-imports-java"
            :fetcher 'github
            :files '(:defaults "sdk" "default"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
