(source "gnu")
(source "melpa")

(package "exec"
         "0.0.1"
         "Test project for command exec")

(package-file "exec.el")

(depends-on "emacs" "26.1")
(depends-on "github-elpa")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
