(package "exec"
         "0.0.1"
         "Test project for command exec")
		 
(website-url "https://github.com/emacs-eask/exec")
(keywords "exec")

(package-file "exec.el")

(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "ert-runner")
(depends-on "github-elpa")

(exec-paths "./bin/")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
