name: Docs

on:
  push:
    branches:
      - master
      - docs
    paths:
      - '**/docs.yml'
      - docs/**
  pull_request:
    branches:
      - master
    paths:
      - '**/docs.yml'
      - docs/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PATH_DOC: ${{ github.workspace }}/emacs-eask.github.io

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - uses: actions/setup-node@v6
      with:
        node-version: 22

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.134.2'

    - name: Build theme
      working-directory: ./docs/themes/geekdoc
      run: |
        npm install
        npm run build

    - name: Check out GitHub page repo
      uses: actions/checkout@v5
      if: github.ref == 'refs/heads/master'
      with:
        repository: emacs-eask/emacs-eask.github.io
        path: ${{ env.PATH_DOC }}
        token: ${{ secrets.PAT }}

    - name: Clean up before the build
      working-directory: ${{ env.PATH_DOC }}
      continue-on-error: true
      run: git rm -r '*'

    - name: Build doc artifacts with Hugo
      working-directory: docs
      run: |
        mkdir -p ${{ env.PATH_DOC }}
        hugo --destination ${{ env.PATH_DOC }} --minify

    # TODO: Generate better commit message
    - name: Publish doc artifacts
      if: github.ref == 'refs/heads/master'
      working-directory: ${{ env.PATH_DOC }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -F- <<-_UBLT_COMMIT_MSG_
        auto: ${{ github.event.head_commit.message }}

        SourceCommit: https://github.com/emacs-eask/cli/commit/${{ github.sha }}
        _UBLT_COMMIT_MSG_
        git push
